#!/bin/sh -x
#   Copyright 2025 SAS Institute, Inc., Cary, NC USA
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#  preinstall.sh
#  CloudLAPS
#
#  Created by Henry Kon on 5/30/24.
#  edited Daniel Reis 7/30

# Check if CloudLAPS is already installed and, if so, suspend the launch daemon and remove the old product completely.
if [ -e "/usr/local/catalyst/Applications/catalyst.app" ]
then
    echo "Suspending existing CloudLAPS launch daemon"
    launchctl unload /Library/LaunchDaemons/com.sas.catalyst-run.plist
    sudo killall "/usr/local/catalyst/Applications/catalyst.app"
    echo "Removing old CloudLAPS application assets"
    sudo rm -rf "/usr/local/catalyst"
    if [ -e "/var/root/.catalystkey" ]; then
        echo "Removing old catalyst keyfile"
        sudo rm -f "/var/root/.catalystkey"
    fi
    sudo pkgutil --forget com.sas.catalyst
fi

